### PR TITLE
UICIRC-372 - Create/Edit loan policy | Move Save/Cancel buttons to the footer

### PR DESCRIPTION
**Pull request by maximdidenkoepam**
# Purpose
Move navigation buttons to the form footer.

# Link
https://issues.folio.org/browse/UICIRC-372

# Screenshot
Screen Shot 2019-10-28 at 14 43 07

### CODE REVIEW

**Comment by VictorSoroka1** [comment]
@maximdidenko, I would recommend adding an entry to the changelog file.

**Comment by mkuklis** [comment]
@maximdidenko I noticed that `test/bigtest/tests/loan-policy/loan-policy-delete-test.js` has been removed. Are we not able to remove loan policy anymore?

**Comment by maximdidenkoepam** [comment]
@mkuklis we don't have an ability to remove any entity form edit screen. But we have it on view screen and this functionality is a part of EntryManager.

**Comment by zburke** [comment]
@maximdidenkoepam please update the [loan renewal integration test in platform-core](/folio-org/platform-core/tree/snapshot/test/ui-testing/loan-renewal.js) that relies on the old `#clickable-create-entry` attribute. It should be a trivial change.

The PR should be issued against the `snapshot` branch.

**Comment by maximdidenkoepam** [comment]
@zburke will do

**Pull request merged**
