### PR TITLE
UICIRC-685 - Change setting "Loan history" setting to "Loan anonymization"

### PR DESCRIPTION
**Pull request by Terala-Priyanka**
## Purpose
Change setting "Loan history" setting to "Loan anonymization"
Issue: [UICIRC-685](https://issues.folio.org/browse/UICIRC-685)

## Screenshots
image

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by NikitaSedyx** [comment]
I think it's good idea to change url path as well from location-history to location-anonymization

@Dmitriy-Litvinenko what do you think?

**Review by Dmitriy-Litvinenko — APPROVED** [review]

**Review by artem-blazhko — APPROVED** [review]

**Comment by Dmitriy-Litvinenko** [comment]
> I think it's good idea to change url path as well from location-history to location-anonymization
> 
> @Dmitriy-Litvinenko what do you think?

Hello @NikitaSedyx Thank you, good question. I don't have any objection if you want change url path from loan-history to loan-anonymization and change translation key from settings.index.loanHistory to settings.index.loanAnonymization.
CC: @artem-blazhko , @Terala-Priyanka

**Comment by Terala-Priyanka** [comment]
> > I think it's good idea to change url path as well from location-history to location-anonymization
> > @Dmitriy-Litvinenko what do you think?
> 
> Hello @NikitaSedyx Thank you, good question. I don't have any objection if you want change url path from loan-history to loan-anonymization and change translation key from settings.index.loanHistory to settings.index.loanAnonymization, but could you please double check that we don't use this url path and translation key in other part of our application(other ui modules) CC: @artem-blazhko , @Terala-Priyanka

@NikitaSedyx @Dmitriy-Litvinenko @artem-blazhko 
1. I did check on the route and looks like it is being used in jest and bigtests.
2. I did check on the translation key as well. 
How ? - 
image
This search was not giving the instances of ui-circulation too. Hence I do not want to rely on this type of search.
Please suggest if there is a better way to search for it.

**Comment by NikitaSedyx** [comment]
@Terala-Priyanka if route is used only in tests, it makes sense to change it as well, because it looks strange with page name is not matched with url

**Comment by Terala-Priyanka** [comment]
> @Terala-Priyanka if route is used only in tests, it makes sense to change it as well, because it looks strange with page name is not matched with url. the same for Key

@NikitaSedyx I have updated the changes. Could you please review.

**Review by NikitaSedyx — APPROVED** [review]

**Pull request merged**
