### PR TITLE
UICIRC-543 increment stripes-template-editor for stripes v6 compat

### PR DESCRIPTION
**Pull request by zburke**
The `@folio/stripes-template-editor` dependency was out of sync with the
`@folio/stripes` `v6` peer dep.

Refs [UICIRC-543](https://issues.folio.org/browse/UICIRC-543)

### CODE REVIEW

**Review by maximdidenkoepam — APPROVED** [review]

**Comment by Dmitriy-Litvinenko** [comment]
Hello @zburke 
Could you please clarify what we need to do with current pull request?

**Comment by zburke** [comment]
@Dmitriy-Litvinenko, this PR looks correct to me, so I think the only thing you "need" to do is wait for `stripes-template-editor` `v3` to be released first.

**Comment by Dmitriy-Litvinenko** [comment]
@zburke Thank you
We will release current module without current PR. We create https://issues.folio.org/browse/UICIRC-552 for update stripes-template-editor.
CC: @annamelnyk

**Comment by Dmitriy-Litvinenko** [comment]
Will be fixed in story https://issues.folio.org/browse/UICIRC-575.
Task https://issues.folio.org/browse/UICIRC-552 - Closed as duplicate for https://issues.folio.org/browse/UICIRC-575.

**Pull request closed without merging**
